[[Kerberos_krb5]]
arch = "aarch64"
git-tree-sha1 = "d99491dee4c0fd394323e1ae1c8313c536fd949e"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "701bcfd14ccf06840c4c17ecb8761a4eae44aa1c57c674114832cbf6780ec366"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.aarch64-linux-gnu.tar.gz"
[[Kerberos_krb5]]
arch = "aarch64"
git-tree-sha1 = "ed7f9c4ea4a660d9933751a481b6e823c2a89dfa"
libc = "musl"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "d596691c45d2e63c06e79b60d694c6fc795eb6cbcb3cddff3baf9de9d8649074"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.aarch64-linux-musl.tar.gz"
[[Kerberos_krb5]]
arch = "aarch64"
git-tree-sha1 = "0a1e497e36629cc0c8541abdc85dc0788723cff3"
os = "freebsd"

    [[Kerberos_krb5.download]]
    sha256 = "a20b17ac26fb9d1527699ab6b63e87bcb75a11c2a2b506091d416f680f7186ce"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.aarch64-unknown-freebsd.tar.gz"
[[Kerberos_krb5]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6e6155ec34bf6902ea092467cf9962d26daba55"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "029e1079d215b4bb579ff01b593a212a835e14e266f2a67e5ad0f5641937e352"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.armv6l-linux-gnueabihf.tar.gz"
[[Kerberos_krb5]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66f374f7d9772262717bed25127bd14e4658a342"
libc = "musl"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "b0d77ca3db15df5ea7c803a0d4cb93003996098089327bfd5e0e041346694571"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.armv6l-linux-musleabihf.tar.gz"
[[Kerberos_krb5]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b883d464bcb1900aff8c045f4a564fd7e68490a7"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "3e8cbba30a384c58e7d395ed4036bd0494916f30e4674c285ac0eafd6ae72b53"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.armv7l-linux-gnueabihf.tar.gz"
[[Kerberos_krb5]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0651358800793c5ad50ded2a41955b2340d3b794"
libc = "musl"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "a3f7cdcf3cff457f4a4c107182e990b58e63dbfc06ed8f097dee0cd7ac1d1709"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.armv7l-linux-musleabihf.tar.gz"
[[Kerberos_krb5]]
arch = "i686"
git-tree-sha1 = "a6b40268386db10d666bac606a6fcd26b9fe1d9b"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "9698b1c53d93f2e0e505734fb2fe085f13bf9bb6260d07467de31587b1b770c8"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.i686-linux-gnu.tar.gz"
[[Kerberos_krb5]]
arch = "i686"
git-tree-sha1 = "c433242f1eaf2e779111e5eb75f7f1556a34a4cb"
libc = "musl"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "93916fb7b099556de0cb59fe3db6577ecb7b0b615ed7d47ef2a0855508fff001"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.i686-linux-musl.tar.gz"
[[Kerberos_krb5]]
arch = "powerpc64le"
git-tree-sha1 = "76fe848f332ad22abc77018a30988f5d9974c0db"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "967b694234694cd97bf1de17b72b8ead23469f8e768f60a562420d3e8461f3de"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.powerpc64le-linux-gnu.tar.gz"
[[Kerberos_krb5]]
arch = "riscv64"
git-tree-sha1 = "4b23db0eece809d10ef7092466869e30a7c98b6c"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "66605258af1d02c6dd93cebc25899dc6b0276c731618a9e98e323dc97fbfe147"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.riscv64-linux-gnu.tar.gz"
[[Kerberos_krb5]]
arch = "x86_64"
git-tree-sha1 = "c57fcc586e2ec0e06393c83b97ebf6937e986bd7"
libc = "glibc"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "1005d7ddeec7459be00f6157749523179bd8b12d85bd14248cd041f4d91145fa"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.x86_64-linux-gnu.tar.gz"
[[Kerberos_krb5]]
arch = "x86_64"
git-tree-sha1 = "02cb5b9397b7a8139496f85e25c4895a50d6bebd"
libc = "musl"
os = "linux"

    [[Kerberos_krb5.download]]
    sha256 = "31127d24f1f7cf31550251511d7402e2071f452d184364db3ff0da228e574f61"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.x86_64-linux-musl.tar.gz"
[[Kerberos_krb5]]
arch = "x86_64"
git-tree-sha1 = "9f482133c1981a32c17ba3605c1677f3b8dd5d4e"
os = "freebsd"

    [[Kerberos_krb5.download]]
    sha256 = "a89e323e93e762c344da224a72b86c12b8be6e6f0116f653ae6b2d0a7c357974"
    url = "https://github.com/JuliaBinaryWrappers/Kerberos_krb5_jll.jl/releases/download/Kerberos_krb5-v1.21.3+0/Kerberos_krb5.v1.21.3.x86_64-unknown-freebsd.tar.gz"
